CREATE TABLE IF NOT EXISTS resultats (
  'id'      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  'created' DATE    DEFAULT CURRENT_TIMESTAMP,
  'json'    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS jornades (
  'id'      INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
  'created' DATETIME DEFAULT CURRENT_TIMESTAMP,
  'json'    TEXT     NOT NULL
);
